site_name: OPENSEIZE

# custom color scheme
extra_css:
    - stylesheets/extra_styles.css

# declare plugins
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    members_order: source
    - mkdocs-jupyter

# declare extensions
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

# use standard material theme
theme:
    name: material

    # two toggleable color palettes
    palette:
        - scheme: space
          toggle:
            icon: material/brightness-7
            name: Dark Mode

        - scheme: slate
          primary: black
          toggle:
              icon: material/brightness-4
              name: Light Mode

    # logos at site name & window tab
    logo: 'imgs/tinylogo.png'
    favicon: 'imgs/tinylogo.png'

    features:
        # add tabs to header & keep visible on scroll
        - navigation.tabs
        - navigation.tabs.sticky

    # add icon to header for github repo link
    icon:
        repo: fontawesome/brands/github

# link to github repository
repo_url: https://github.com/mscaudill/openseize
repo_name: mscaudill/openseize

# make pages non-editable
edit_uri: ""

# configure navigation pane
nav:
    - Home: index.md
    - Quickstart: quickstart.ipynb
    - Tutorials:
        - 'Producers': 'tutorials/producers.ipynb'
        - 'File Reading': 'tutorials/file_reading.ipynb'
        - 'Filtering': 'tutorials/filtering.ipynb'
        - 'Resampling': 'tutorials/resampling.ipynb'
        - 'Fourier Transform': 'tutorials/fourier_transform.ipynb'
        - 'Spectral Analysis': 'tutorials/spectra.ipynb'
    - Reference:
        - Producers:
          - producer: 'producer.md'
        - 'File IO':
          - EDF: 
            - Introduction: 'file_io/edf_intro.md' 
            - Reader: 'file_io/edf_reader.md'
            - Writer: 'file_io/edf_writer.md'
            - Splitter: 'file_io/edf_splitter.md'
        - Filters:
            - 'FIR Filters':
              - Introduction: 'firs/info.md' 
              - Kaiser: 'firs/kaiser.md'
              - Rectangular: 'firs/rectangular.md'
              - Bartlett: 'firs/bartlett.md'
              - Hann: 'firs/hann.md'
              - Hamming: 'firs/hamming.md'
              - Blackman: 'firs/blackman.md'
              - Remez: 'firs/remez.md'
            - 'IIR Filters':
              - Introduction: 'iirs/info.md'
              - Butterworth: 'iirs/butter.md'
              - 'Chebyshev I': 'iirs/cheby1.md'
              - 'Chebyshev II': 'iirs/cheby2.md'
              - Elliptical: 'iirs/ellip.md'
              - Notch: 'iirs/notch.md'
    - About: about.md

# reflect changes immediately during dev.
watch: 
    - src/openseize/

# Footer icon components
extra:
    social:
        - icon: fontawesome/brands/github 
          link: https://github.com/mscaudill


