#requirements for the openseize package
name: openseize
dependencies:
    - numpy
    - scipy
    - matplotlib
    - ipython
    - notebook
    - pandas
    - pytest
    - scikit-learn
    - psutil # only for siftnets support
